"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type RoomData={subject:string;property:string|null;participant:string;expiresAt:string;messages:Array<{id:string;sender_name:string;sender_type:string;body:string;delivery_status:string;created_at:string}>};

export function ClientRoom({token}:{token:string}){
  const [room,setRoom]=useState<RoomData|null>(null),[error,setError]=useState(""),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const response=await fetch(`/api/client-rooms/${token}`,{cache:"no-store"});const body=await response.json();if(!response.ok){setError(body.error?.message??"This private room is unavailable.");return}setRoom(body.data)},[token]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  async function send(event:FormEvent){event.preventDefault();if(!draft.trim())return;setBusy(true);const text=draft.trim();const response=await fetch(`/api/client-rooms/${token}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:text})});const body=await response.json();setBusy(false);if(!response.ok){setError(body.error?.message??"The message could not be posted.");return}setDraft("");await load()}
  if(error)return <main className="client-room-page"><div className="client-room-error"><b>VOYNUE</b><h1>Private room unavailable.</h1><p>{error}</p></div></main>;
  if(!room)return <main className="client-room-page"><div className="client-room-loading"><i/><span>Opening your secure room…</span></div></main>;
  return <main className="client-room-page"><section className="client-room-shell"><header><div><b>VOYNUE</b><span>PRIVATE STAY ROOM</span></div><small>Link expires {new Date(room.expiresAt).toLocaleDateString()}</small></header><div className="client-room-heading"><span>{room.property??"Guest communication"}</span><h1>{room.subject}</h1><p>Welcome, {room.participant}. Messages in this room are shared only with invited participants and the property team.</p></div><div className="client-message-stream">{room.messages.length?room.messages.map(message=><article className={message.sender_type==="guest"?"guest-message":"host-message"} key={message.id}><div><b>{message.sender_name}</b><time>{new Date(message.created_at).toLocaleString()}</time></div><p>{message.body}</p><small>{message.delivery_status}</small></article>):<div className="client-room-empty"><i>⌁</i><b>Your private room is ready.</b><span>Send the first message to your host.</span></div>}</div><form onSubmit={send}><label className="sr-only" htmlFor="client-room-message">Message</label><textarea id="client-room-message" value={draft} onChange={event=>setDraft(event.target.value)} placeholder="Write a message to your host…" maxLength={10000}/><div><span>Private · Secured by an expiring link</span><button disabled={busy||!draft.trim()}>{busy?"Sending…":"Send"} ↑</button></div></form></section></main>;
}
