"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Provider="in_app"|"email"|"airbnb_draft"|"whatsapp"|"instagram"|"facebook"|"sms";
type Message={id:string;sender_name:string;sender_type:string;direction:string;provider:Provider;body:string;delivery_status:string;error_message:string|null;created_at:string};
type Conversation={id:string;subject:string;provider:Provider;status:string;unreadCount:number;lastMessageAt:string;property:string|null;participants:Array<{display_name:string;email:string|null;role:string}>;messages:Message[]};
type InboxResponse={conversations:Conversation[];providerStatus:Record<Provider,string>};
const providerMeta:Record<Provider,{label:string;icon:string;color:string}>={in_app:{label:"Private rooms",icon:"⌁",color:"#0878f9"},email:{label:"Email",icon:"✉",color:"#775cff"},airbnb_draft:{label:"Airbnb drafts",icon:"A",color:"#ff5a5f"},whatsapp:{label:"WhatsApp",icon:"W",color:"#21b869"},instagram:{label:"Instagram",icon:"I",color:"#d94a89"},facebook:{label:"Facebook",icon:"F",color:"#3478e5"},sms:{label:"SMS",icon:"S",color:"#d18a24"}};

export function CommunicationsInbox({locale}:{locale:string}){
  const es=locale==="es";
  const [data,setData]=useState<InboxResponse|null>(null),[activeId,setActiveId]=useState(""),[filter,setFilter]=useState<"all"|Provider>("all"),[query,setQuery]=useState(""),[draft,setDraft]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[creating,setCreating]=useState(false),[subject,setSubject]=useState(""),[participant,setParticipant]=useState(""),[email,setEmail]=useState(""),[provider,setProvider]=useState<"in_app"|"email"|"airbnb_draft">("in_app"),[invite,setInvite]=useState("");
  const load=useCallback(async()=>{setLoading(true);const response=await fetch("/api/conversations",{cache:"no-store"});const body=await response.json();setLoading(false);if(!response.ok){setNotice(body.error?.message??"Messages could not load.");return}setData(body.data);setActiveId(current=>current||body.data.conversations[0]?.id||"")},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const filtered=useMemo(()=>data?.conversations.filter(item=>(filter==="all"||item.provider===filter)&&`${item.subject} ${item.property??""} ${item.participants.map(p=>p.display_name).join(" ")}`.toLowerCase().includes(query.toLowerCase()))??[],[data,filter,query]);
  const active=data?.conversations.find(item=>item.id===activeId)??filtered[0];

  async function create(event:FormEvent){event.preventDefault();setNotice("");const response=await fetch("/api/conversations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",subject,participantName:participant,participantEmail:email||undefined,provider})});const body=await response.json();if(!response.ok){setNotice(body.error?.message??"Conversation could not be created.");return}setInvite(body.data.inviteUrl??"");setCreating(false);setSubject("");setParticipant("");setEmail("");await load();setActiveId(body.data.conversationId)}
  async function send(event:FormEvent){event.preventDefault();if(!active||!draft.trim())return;const text=draft.trim();setDraft("");setNotice("");const response=await fetch("/api/conversations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"message",conversationId:active.id,body:text})});const body=await response.json();if(!response.ok){setDraft(text);setNotice(body.error?.message??"Message could not be completed.");return}setNotice(body.data.delivery==="draft"?(es?"Borrador guardado. Cópialo en Airbnb manualmente.":"Draft saved. Copy it into Airbnb manually."):(es?"Mensaje procesado correctamente.":"Message processed successfully."));await load()}

  return <div className="communications-page">
    <header className="communications-title"><div><p>VOYNUE COMMUNICATIONS</p><h1>{es?"Todas las conversaciones. Un solo lugar.":"Every conversation. One place."}</h1><span>{es?"Salas privadas, correo real y borradores honestos para canales sin integración autorizada.":"Private rooms, real email, and honest drafts for channels without authorized integrations."}</span></div><button onClick={()=>setCreating(true)}>＋ {es?"Nueva conversación":"New conversation"}</button></header>
    <div className="channel-health">{(["in_app","email","airbnb_draft","whatsapp","instagram","facebook","sms"] as Provider[]).map(item=>{const meta=providerMeta[item],status=data?.providerStatus[item]??"setup_required";return <button key={item} className={filter===item?"active":""} onClick={()=>setFilter(filter===item?"all":item)} style={{"--channel-color":meta.color} as React.CSSProperties}><i>{meta.icon}</i><span><b>{meta.label}</b><small>{status.replaceAll("_"," ")}</small></span><em className={status}/></button>})}</div>
    {notice&&<div className="communications-notice"><span>ⓘ {notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
    {invite&&<div className="communications-invite"><span><b>{es?"Enlace privado listo":"Private invite ready"}</b><code>{invite}</code></span><button onClick={()=>void navigator.clipboard.writeText(invite)}>{es?"Copiar":"Copy"}</button><button onClick={()=>setInvite("")}>×</button></div>}
    <section className="inbox-voynue">
      <aside className="voynue-thread-list"><div className="inbox-query"><i>⌕</i><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={es?"Buscar conversaciones":"Search conversations"}/></div>{loading?<div className="communications-empty"><i/><span>{es?"Cargando…":"Loading…"}</span></div>:filtered.map(item=>{const meta=providerMeta[item.provider],last=item.messages.at(-1);return <button key={item.id} className={active?.id===item.id?"active":""} onClick={()=>setActiveId(item.id)}><i style={{background:meta.color}}>{meta.icon}</i><span><b>{item.subject}</b><small>{item.property??meta.label}</small><em>{last?.body??(es?"Sin mensajes todavía":"No messages yet")}</em></span><time>{new Date(item.lastMessageAt).toLocaleDateString()}</time>{item.unreadCount>0&&<strong>{item.unreadCount}</strong>}</button>})}{!loading&&!filtered.length&&<div className="communications-empty"><i>⌁</i><b>{es?"No hay conversaciones reales todavía.":"No real conversations yet."}</b><span>{es?"Crea una sala privada, correo o borrador.":"Create a private room, email, or draft."}</span></div>}</aside>
      <article className="voynue-message-panel">{active?<><header><i style={{background:providerMeta[active.provider].color}}>{providerMeta[active.provider].icon}</i><div><b>{active.subject}</b><span>{providerMeta[active.provider].label} · {active.participants.map(p=>p.display_name).join(", ")}</span></div><em><i/> {active.status}</em></header><div className="voynue-message-stream">{active.messages.length?active.messages.map(message=><div key={message.id} className={message.sender_type==="host"||message.sender_type==="team"?"message-mine":"message-theirs"}><div><b>{message.sender_name}</b><time>{new Date(message.created_at).toLocaleString()}</time></div><p>{message.body}</p><small>{message.delivery_status}{message.provider==="airbnb_draft"?" · not sent":""}</small></div>):<div className="communications-empty large"><i>⌁</i><b>{es?"La conversación está lista.":"The conversation is ready."}</b><span>{active.provider==="airbnb_draft"?(es?"Los mensajes se guardan como borrador, no se envían a Airbnb.":"Messages are saved as drafts, not sent to Airbnb."):(es?"Escribe el primer mensaje.":"Write the first message.")}</span></div>}</div><form onSubmit={send}><textarea value={draft} onChange={event=>setDraft(event.target.value)} placeholder={active.provider==="airbnb_draft"?(es?"Redactar para copiar en Airbnb…":"Draft to copy into Airbnb…"):(es?"Escribir un mensaje…":"Write a message…")}/><div><span>{active.provider==="email"?(data?.providerStatus.email==="connected"?(es?"Se enviará por Resend":"Will send through Resend"):(es?"Configuración de Resend requerida":"Resend setup required")):active.provider==="airbnb_draft"?(es?"Solo borrador · No envío directo":"Draft only · No direct delivery"):(es?"Sala privada VOYNUE":"Private VOYNUE room")}</span><button disabled={!draft.trim()}>{active.provider==="airbnb_draft"?(es?"Guardar borrador":"Save draft"):(es?"Enviar":"Send")} ↑</button></div></form></>:<div className="communications-empty large"><i>⌁</i><b>{es?"Selecciona una conversación.":"Select a conversation."}</b><span>{es?"Los mensajes permanecen conectados a la estancia correcta.":"Messages stay connected to the correct stay."}</span></div>}</article>
      <aside className="conversation-info">{active?<><span>{es?"CONVERSACIÓN":"CONVERSATION"}</span><h3>{active.subject}</h3><div><small>{es?"Canal":"Channel"}</small><b>{providerMeta[active.provider].label}</b></div><div><small>{es?"Propiedad":"Property"}</small><b>{active.property??(es?"No vinculada":"Not linked")}</b></div><div><small>{es?"Participantes":"Participants"}</small>{active.participants.map(person=><p key={`${person.display_name}-${person.role}`}><i>{person.display_name.slice(0,1)}</i><span><b>{person.display_name}</b><small>{person.role}</small></span></p>)}</div><p className="communication-disclosure">{active.provider==="airbnb_draft"?(es?"VOYNUE no afirma tener mensajería directa con Airbnb. Este hilo guarda borradores para copiar manualmente.":"VOYNUE does not claim direct Airbnb messaging. This thread stores drafts for manual copy."):(es?"La entrega externa solo ocurre mediante un proveedor realmente configurado.":"External delivery occurs only through a provider that is actually configured.")}</p></>:<div className="communications-empty"/>}</aside>
    </section>
    {creating&&<div className="communications-modal-backdrop"><form className="communications-modal" onSubmit={create}><header><div><span>VOYNUE COMMUNICATIONS</span><h2>{es?"Nueva conversación":"New conversation"}</h2></div><button type="button" onClick={()=>setCreating(false)}>×</button></header><div className="channel-choice">{(["in_app","email","airbnb_draft"] as const).map(item=><button type="button" key={item} className={provider===item?"active":""} onClick={()=>setProvider(item)}><i style={{background:providerMeta[item].color}}>{providerMeta[item].icon}</i><span><b>{providerMeta[item].label}</b><small>{item==="in_app"?(es?"Enlace seguro de 7 días":"Secure 7-day invite"):item==="email"?(es?"Requiere Resend":"Requires Resend"):(es?"No se envía directamente":"Never sent directly")}</small></span></button>)}</div><label><span>{es?"Asunto":"Subject"}</span><input required minLength={3} value={subject} onChange={event=>setSubject(event.target.value)} placeholder={es?"Estancia de la familia Rivera":"Rivera family stay"}/></label><label><span>{es?"Nombre del participante":"Participant name"}</span><input required value={participant} onChange={event=>setParticipant(event.target.value)} placeholder="Sofia Rivera"/></label>{(provider==="email"||provider==="in_app")&&<label><span>{es?"Correo":"Email"}</span><input required={provider==="email"} type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="guest@example.com"/></label>}<footer><button type="button" onClick={()=>setCreating(false)}>{es?"Cancelar":"Cancel"}</button><button>{es?"Crear conversación":"Create conversation"} →</button></footer></form></div>}
  </div>;
}
