"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { brand, packages, services } from "@/lib/brand";

const details: Record<string, { title: string; intro: string; bullets: string[]; note?: string }> = {
  "interior-design-concepts": { title: "Interior Design Concepts", intro: "A visual direction for the spaces that matter most—made clear enough to act on.", bullets: ["Mood boards", "Room-by-room vision", "Furniture and décor direction", "Color and lighting ideas", "Shopping-list guidance", "Delivery inside Maison AI"], note: "ROSALT provides design concepts and planning support, not architectural or licensed construction services." },
  "airbnb-styling": { title: "Airbnb Styling", intro: "Make the property feel photo-worthy, guest-friendly, and ready to be remembered.", bullets: ["Bedroom refresh plans", "Coffee-bar and amenity concepts", "Bathroom moments", "Photo-worthy corners", "Guest flow and experience", "Seasonal refresh ideas"] },
  "property-refurbishment": { title: "Property Refurbishment Planning", intro: "Turn a property’s potential into a practical refresh or remodel vision before work begins.", bullets: ["Before-and-after vision", "Priority upgrade list", "Material and style direction", "Budget-range planning", "Contractor-ready scope notes", "Timeline concept"], note: brand.disclaimer },
  "photography-content": { title: "Photography & Content", intro: "Make the property work as beautifully online as it does in person.", bullets: ["Airbnb listing photo direction", "Real-estate content", "Before-and-after concepts", "Reels and TikTok ideas", "Property brand direction", "Caption and listing-copy support"] },
  "contractor-coordination": { title: "Contractor Coordination", intro: "A polished project vision that is easier to share, quote, approve, and track.", bullets: ["Scope preparation", "Inspiration boards", "Contractor-ready notes", "Vendor recommendations", "Client approvals", "Status and communication notes"], note: "ROSALT does not guarantee contractor performance and does not replace licensed trades. We organize the vision and referral process." },
};

export function ServicesPage({ locale }: { locale: string }) { return <PageShell eyebrow="Studio services" title="A property vision, made actionable." intro="Each ROSALT service can stand alone or become part of a complete property transformation."><div className="maison-grid">{services.map(([slug, title, body], i) => <Link className="maison-card" href={`/${locale}/services/${slug}`} key={slug}><span>0{i + 1}</span><h3>{title}</h3><p>{body}</p><b>Learn more →</b></Link>)}</div></PageShell>; }

export function ServicePage({ locale, service }: { locale: string; service: string }) { const d = details[service]; if (!d) return null; return <PageShell eyebrow="ROSALT service" title={d.title} intro={d.intro}><div className="maison-detail"><div><p className="maison-label">Included direction</p>{d.bullets.map((b, i) => <div className="maison-line" key={b}><span>0{i + 1}</span>{b}</div>)}</div><aside><p>Delivered through Maison AI</p><h3>One clear project portal.</h3><p>Keep inspiration, visual direction, notes, files, approvals, and the next steps in one private place.</p><Link href={`/${locale}/start-project`}>Start a project →</Link></aside></div>{d.note && <p className="maison-disclaimer">{d.note}</p>}</PageShell>; }

export function PackagesPage({ locale }: { locale: string }) { return <PageShell eyebrow="Studio packages" title="Choose the level of transformation." intro="Clear starting points for a single room, a guest-ready stay, or a full property concept."><div className="maison-grid packages">{packages.map(([name, price, body]) => <article className="maison-card" key={name}><span>{price}</span><h3>{name}</h3><p>{body}</p><Link href={`/${locale}/start-project`}>Start your vision →</Link></article>)}</div></PageShell>; }

export function MaisonAiPage({ locale }: { locale: string }) { const tools = ["AI property intake", "Client design portal", "Design package builder", "Mood board organizer", "Airbnb styling planner", "Contractor scope generator", "Photography and content planner", "Guest & Client CRM", "Readiness workflows", "Tasks, files, upgrades, and stays"]; return <PageShell eyebrow="Private client platform" title="Maison AI turns an idea into an organized property plan." intro="The software layer behind ROSALT: from first photos and inspiration to design delivery, guest experience, and ongoing property operations."><div className="maison-tool"><div><p className="maison-label">Maison AI workspace</p><h3>Property Vision<br/>in progress</h3><div className="maison-progress"><i/><i/><i/><i/></div><small>Intake · Direction · Scope · Launch</small></div><section>{tools.map((tool, i) => <div className="maison-line" key={tool}><span>{String(i + 1).padStart(2, "0")}</span>{tool}</div>)}<Link href={`/${locale}/demo`}>Preview Maison AI →</Link></section></div></PageShell>; }

export function AboutPage() { return <PageShell eyebrow="About ROSALT" title="Two women. One vision for better spaces." intro="ROSALT is a signature name created from the founders’ names: ROS represents Rosehna. ALT represents Altamirano."><div className="maison-detail founders"><article><span>ROSEHNA</span><h3>Creative direction</h3><p>Rosehna brings a creative eye for interiors, styling, and the feeling a space gives when someone walks in. Her focus is helping properties feel beautiful, intentional, and ready to impress guests, buyers, or homeowners.</p></article><article><span>ALTAMIRANO</span><h3>Brand, operations & technology</h3><p>Altamirano brings the vision for brand, operations, content, and technology. Her focus is helping turn property ideas into organized plans, polished content, and scalable systems through Maison AI.</p></article></div><p className="maison-disclaimer">ROSALT Maison Studios represents two women bringing one vision together: creating beautiful homes, elevated stays, and property experiences that feel intentional, profitable, and memorable.</p></PageShell>; }

export function StartProjectPage() { const [sent, setSent] = useState(false); const [saved, setSaved] = useState(false); useEffect(() => { setSaved(Boolean(localStorage.getItem("maison-project-draft"))); }, []); return <PageShell eyebrow="Start a project" title="Start your Property Vision." intro="Tell us what you are planning. Your brief saves privately in this browser until your Maison AI workspace is connected."><form className="maison-form" onSubmit={(e) => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); localStorage.setItem("maison-project-draft", JSON.stringify(data)); setSent(true); setSaved(true); }}><div>{["Name", "Email", "Phone", "Property address or city", "Property type", "Budget range", "Timeline"].map((x) => <label key={x}>{x}<input name={x.toLowerCase().replaceAll(" ", "-")} required={x === "Name" || x === "Email"} placeholder={x}/></label>)}</div><label>Project type<select name="project-type"><option>Airbnb / short-term rental</option><option>Real estate</option><option>Refurbishment / remodel vision</option><option>Rental property</option><option>Personal home</option></select></label><label>Services interested in<textarea name="services" placeholder="Interior concepts, Airbnb styling, photography, contractor coordination…"/></label><label>Project notes<textarea name="notes" placeholder="Tell us about the property, goals, and the feeling you want it to have."/></label><button type="submit">{sent ? "Project brief saved locally" : "Save Your Property Vision →"}</button>{(sent || saved) && <p className="maison-form-note">Your private browser draft is saved. Connect Supabase to store and route real client submissions into Maison AI.</p>}</form></PageShell>; }

export function DemoPage({ locale }: { locale: string }) { const [stage, setStage] = useState(0); const [done, setDone] = useState<number[]>([]); const stages = ["Property intake", "Design package", "Styling checklist", "Readiness workflow", "Guest & client profile", "Content checklist", "Contractor scope"]; const active = stages[stage]; const mark = () => setDone((items) => items.includes(stage) ? items.filter((item) => item !== stage) : [...items, stage]); return <PageShell eyebrow="Interactive sandbox" title="Maison AI Demo" intro="A safe preview of how Maison AI organizes a property project. Sample data only—nothing here is saved to a real account."><div className="maison-demo"><div>{stages.map((x, i) => <button className={i === stage ? "active" : ""} onClick={() => setStage(i)} key={x}><span>{done.includes(i) ? "✓" : String(i + 1).padStart(2, "0")}</span>{x}</button>)}</div><section><p className="maison-label">{active} · {done.length}/7 complete</p><h3>{stage === 0 ? "Describe the opportunity." : stage === 1 ? "See the design direction." : stage === 2 ? "Make every corner photo-ready." : stage === 3 ? "Confirm the space is ready." : stage === 4 ? "Keep every relationship in context." : stage === 5 ? "Plan the story before shooting." : "Turn inspiration into scope notes."}</h3><p>Explore the workspace in steps, then mark the item reviewed. Existing dashboards, CRM, files, tasks, and readiness logic remain available when a real account is connected.</p><div className="maison-demo-actions"><button onClick={mark}>{done.includes(stage) ? "Mark as not reviewed" : "Mark reviewed"}</button>{stage < stages.length - 1 && <button onClick={() => setStage(stage + 1)}>Next step →</button>}</div><Link href={`/${locale}/dashboard`}>Open Maison AI Dashboard →</Link></section></div></PageShell>; }

function PageShell({ eyebrow, title, intro, children }: { eyebrow: string; title: string; intro: string; children: React.ReactNode }) { return <main className="maison-page"><section className="maison-hero"><p>{eyebrow}</p><h1>{title}</h1><span>{intro}</span></section>{children}</main>; }
