"use client";

import Link from "next/link";
import { useState } from "react";
import { Header } from "@/components/header";

export function RosaltHome({ locale }: { locale: string }) {
  const [budget, setBudget] = useState(7500);
  const [mode, setMode] = useState<"Vision" | "Refresh" | "Launch">("Vision");
  const allocation: Array<[string, number]> = [["Design direction", 38], ["Styling & furnishings", 28], ["Content & launch", 18], ["Project reserve", 16]];
  return <div className="rosalt-product-home">
    <div className="rosalt-topline"><span>ROSALT MAISON STUDIOS · NASHVILLE</span><Link href={`/${locale}/start-project`}>Start a Property Project ↗</Link></div>
    <Header locale={locale}/>
    <main>
      <section className="rosalt-hero"><div className="rosalt-hero-copy"><p className="rosalt-kicker"><i/> PROPERTY TRANSFORMATION STUDIO</p><h1>Design the property.<br/><em>Run the vision.</em></h1><p className="rosalt-lede">ROSALT brings together interior concepts, Airbnb styling, content direction, and contractor-ready planning—organized through Maison AI.</p><div className="rosalt-actions"><Link className="rosalt-button" href={`/${locale}/start-project`}>Start a Property Project <span>→</span></Link><Link className="rosalt-text-link" href={`/${locale}/maison-ai`}>Explore Maison AI <span>↗</span></Link></div><div className="rosalt-proof"><span><b>01</b> Design intelligence</span><span><b>02</b> Private client portal</span><span><b>03</b> Property-first operations</span></div></div><div className="rosalt-hero-system"><div className="rosalt-ra-frame"><img src="/images/rosalt-ra-logo-full.png" alt="ROSALT RA monogram"/></div><div className="rosalt-system-window"><header><span>MAISON AI</span><small>PROPERTY VISION / 01</small><i/></header><div className="rosalt-system-main"><p>ACTIVE PROJECT</p><h2>West End<br/>Guest Suite</h2><div className="rosalt-status"><i/> Design direction in review <b>64%</b></div><div className="rosalt-tasks"><span>01 <b>Mood board locked</b><em>✓</em></span><span>02 <b>Styling selections</b><em>→</em></span><span>03 <b>Content shot list</b><em>→</em></span></div></div></div><div className="rosalt-orbit one"/><div className="rosalt-orbit two"/></div></section>
      <section className="rosalt-command"><div className="rosalt-command-copy"><p className="rosalt-kicker"><i/> MAISON AI LIVE PLANNER</p><h2>Make the investment<br/>visible before it begins.</h2><p>Explore a working project budget. Maison AI keeps the design direction, priority upgrades, scope notes, files, and client decisions in one private workspace.</p><div className="rosalt-mode-tabs">{(["Vision", "Refresh", "Launch"] as const).map((item) => <button key={item} className={mode === item ? "active" : ""} onClick={() => setMode(item)}>{item}</button>)}</div></div><div className="rosalt-budget-console"><header><span>PROJECT INVESTMENT</span><b>{mode.toUpperCase()} MODE</b></header><strong>${budget.toLocaleString()}</strong><input type="range" min="1500" max="25000" step="500" value={budget} onChange={(event) => setBudget(Number(event.target.value))}/><div className="rosalt-budget-range"><span>$1.5k</span><span>$25k</span></div><div className="rosalt-allocation">{allocation.map(([label, amount]) => <div key={label}><span>{label}</span><i><b style={{ width: `${amount}%` }}/></i><em>${Math.round(budget * (amount / 100)).toLocaleString()}</em></div>)}</div><Link href={`/${locale}/demo`}>Open interactive demo <span>→</span></Link></div></section>
      <section className="rosalt-offers"><div><p className="rosalt-kicker"><i/> THE ROSALT METHOD</p><h2>A studio for how a property looks, works, and is remembered.</h2></div><Link href={`/${locale}/services`}>View all services ↗</Link><div className="rosalt-offer-grid"><Link href={`/${locale}/services/interior-design-concepts`}><span>01</span><h3>Interior<br/>Concepts</h3><p>Design direction that gives every room a point of view.</p><em>↗</em></Link><Link href={`/${locale}/services/airbnb-styling`}><span>02</span><h3>Airbnb<br/>Styling</h3><p>More memorable stays through guest-ready, photo-ready details.</p><em>↗</em></Link><Link href={`/${locale}/services/photography-content`}><span>03</span><h3>Content<br/>Direction</h3><p>Images, shots, and launch materials that sell the experience.</p><em>↗</em></Link><Link href={`/${locale}/maison-ai`}><span>04</span><h3>Maison AI<br/>Portal</h3><p>The private operating layer for every project and property.</p><em>↗</em></Link></div></section>
      <section className="rosalt-final"><div><p>ROSALT MAISON STUDIOS</p><h2>Better spaces are<br/>built from better decisions.</h2><Link className="rosalt-button light" href={`/${locale}/start-project`}>Begin your Property Vision <span>→</span></Link></div><img src="/images/rosalt-ra-logo-full.png" alt="ROSALT RA monogram"/></section>
    </main>
  </div>;
}
