begin;
create extension if not exists pgcrypto;
create extension if not exists citext;

create type public.app_role as enum ('traveler','host_owner','host_manager','property_staff','cleaner','maintenance_vendor','experience_vendor','support_agent','admin','super_admin');
create type public.reservation_status as enum ('pending','confirmed','cancelled','blocked','completed');
create type public.job_status as enum ('pending','accepted','declined','in_progress','completed','approved','cancelled');
create type public.approval_status as enum ('pending','approved','rejected','expired','cancelled');
create type public.payment_status as enum ('pending','requires_action','paid','failed','refunded','partially_refunded','disputed','cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text, phone text, preferred_language text not null default 'en' check (preferred_language in ('en','es')),
  timezone text not null default 'America/Chicago', avatar_path text, marketing_opt_in boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table public.roles (role public.app_role primary key, description text not null);
insert into public.roles values
 ('traveler','Traveler and guest planner access'),('host_owner','Organization owner'),('host_manager','Organization manager'),('property_staff','Assigned property staff'),('cleaner','Assigned cleaning work'),('maintenance_vendor','Assigned maintenance work'),('experience_vendor','Approved experience vendor'),('support_agent','Audited support access'),('admin','Audited platform administration'),('super_admin','Infrastructure-controlled platform administration');

create table public.organizations (
  id uuid primary key default gen_random_uuid(), hosting_name text not null, legal_name text, email text not null, phone text,
  preferred_language text not null default 'en' check (preferred_language in ('en','es')), timezone text not null, currency char(3) not null default 'USD', country char(2) not null, state text, city text,
  stripe_customer_id text unique, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table public.organization_members (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade, role public.app_role not null, status text not null default 'active' check (status in ('invited','active','suspended')),
  invited_email citext, joined_at timestamptz, created_at timestamptz not null default now(), unique(organization_id,user_id,role)
);

create table public.properties (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, internal_code text not null, address_line1 text not null, address_line2 text, city text not null, state text not null, postal_code text not null, country char(2) not null,
  latitude numeric(10,7), longitude numeric(10,7), timezone text not null, property_type text not null, bedrooms numeric(5,1) not null default 0, beds integer not null default 0, bathrooms numeric(5,1) not null default 0, max_guests integer not null,
  checkin_time time not null, checkout_time time not null, quiet_hours text, parking_details text, wifi_ssid text, wifi_secret_ciphertext text, emergency_contact text,
  welcome_message text, guidebook_status text not null default 'draft', permit_acknowledged_at timestamptz, insurance_acknowledged_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, unique(organization_id,internal_code)
);
create table public.property_amenities (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, name text not null, details text, unique(property_id,name));
create table public.property_photos (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, storage_path text not null, room_type text, caption text, alt_text text, sort_order integer not null default 0, is_cover boolean not null default false, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.property_rules (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, title text not null, body text not null, sort_order integer not null default 0, active boolean not null default true);
create table public.property_integrations (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, provider text not null, status text not null default 'setup_required', encrypted_config jsonb not null default '{}', last_healthy_at timestamptz, last_error text, created_at timestamptz not null default now(), unique(property_id,provider));

create table public.calendar_sources (
  id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, provider text not null check(provider in ('airbnb','vrbo','booking_ical','other_ical')),
  feed_url_ciphertext text not null, url_fingerprint text not null, active boolean not null default true, sync_interval_minutes integer not null default 60, last_synced_at timestamptz, last_success_at timestamptz, last_error text, created_at timestamptz not null default now(), unique(property_id,url_fingerprint)
);
create table public.reservation_sync_runs (id uuid primary key default gen_random_uuid(), calendar_source_id uuid not null references public.calendar_sources(id) on delete cascade, started_at timestamptz not null default now(), completed_at timestamptz, status text not null default 'running', fetched_count integer not null default 0, inserted_count integer not null default 0, updated_count integer not null default 0, cancelled_count integer not null default 0, error_code text, error_message text, reference_id text not null);
create table public.guests (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, profile_id uuid references public.profiles(id), full_name text, email citext, phone text, preferred_language text not null default 'en', internal_notes text, risk_notes text,
  lifetime_value numeric(12,2) not null default 0, upgrade_value numeric(12,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table public.guest_preferences (id uuid primary key default gen_random_uuid(), guest_id uuid not null references public.guests(id) on delete cascade, interests text[] not null default '{}', total_budget numeric(12,2), occasion text, dietary_preferences text[], accessibility_needs text, transportation_preference text, travel_pace text, updated_at timestamptz not null default now(), unique(guest_id));
create table public.guest_consents (id uuid primary key default gen_random_uuid(), guest_id uuid not null references public.guests(id) on delete cascade, consent_type text not null, status boolean not null, policy_version text not null, captured_at timestamptz not null default now(), revoked_at timestamptz, source text not null, unique(guest_id,consent_type,policy_version));
create table public.reservations (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, property_id uuid not null references public.properties(id) on delete cascade, guest_id uuid references public.guests(id) on delete set null, calendar_source_id uuid references public.calendar_sources(id) on delete set null,
  source text not null, external_id text, source_uid text, source_raw_hash text, arrival_date date not null, departure_date date not null, nights integer generated always as (departure_date-arrival_date) stored,
  adults integer not null default 1, children integer not null default 0, infants integer not null default 0, pets integer not null default 0, status public.reservation_status not null default 'confirmed', payment_status public.payment_status not null default 'pending',
  currency char(3) not null default 'USD', gross_booking_value numeric(12,2), cleaning_fee numeric(12,2), taxes numeric(12,2), host_payout_estimate numeric(12,2), source_fees numeric(12,2), internal_notes text,
  sync_status text not null default 'current', source_updated_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz,
  check(departure_date > arrival_date)
);
create unique index reservations_source_identity on public.reservations(property_id,source,source_uid) where source_uid is not null and deleted_at is null;
create index reservations_property_dates on public.reservations(property_id,arrival_date,departure_date) where deleted_at is null;
create index reservations_org_status on public.reservations(organization_id,status,arrival_date) where deleted_at is null;

create table public.guest_portal_tokens (id uuid primary key default gen_random_uuid(), reservation_id uuid not null references public.reservations(id) on delete cascade, token_hash text not null unique, expires_at timestamptz not null, revoked_at timestamptz, last_accessed_at timestamptz, access_count integer not null default 0, created_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.guest_messages (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), reservation_id uuid references public.reservations(id), sender_user_id uuid references auth.users(id), channel text not null, direction text not null, subject text, body text not null, locale text not null default 'en', status text not null default 'draft', scheduled_for timestamptz, sent_at timestamptz, provider_message_id text, error_message text, created_at timestamptz not null default now());

create table public.trip_plans (id uuid primary key default gen_random_uuid(), owner_user_id uuid references auth.users(id), reservation_id uuid references public.reservations(id) on delete set null, organization_id uuid references public.organizations(id) on delete set null, destination text not null, start_date date not null, end_date date not null, travelers integer not null, total_budget numeric(12,2) not null, activity_budget numeric(12,2) not null, style text not null, interests text[] not null, locale text not null default 'en', share_token_hash text unique, share_expires_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.trip_days (id uuid primary key default gen_random_uuid(), trip_plan_id uuid not null references public.trip_plans(id) on delete cascade, day_date date not null, title text, sort_order integer not null, unique(trip_plan_id,day_date));
create table public.trip_items (id uuid primary key default gen_random_uuid(), trip_day_id uuid not null references public.trip_days(id) on delete cascade, item_type text not null, title text not null, starts_at timestamptz, ends_at timestamptz, address text, latitude numeric(10,7), longitude numeric(10,7), estimated_cost numeric(12,2) not null default 0, currency char(3) not null default 'USD', provider text not null, provider_record_id text not null, factual_url text, ai_notes text, sort_order integer not null, created_at timestamptz not null default now());
create table public.trip_collaborators (id uuid primary key default gen_random_uuid(), trip_plan_id uuid not null references public.trip_plans(id) on delete cascade, user_id uuid references auth.users(id), email citext, permission text not null default 'view', invited_at timestamptz not null default now(), accepted_at timestamptz);

create table public.events (id uuid primary key default gen_random_uuid(), provider text not null, provider_id text not null, name text not null, category text, venue text, address text, latitude numeric(10,7), longitude numeric(10,7), starts_at timestamptz not null, timezone text, ticket_url text, image_url text, price_min numeric(12,2), price_max numeric(12,2), currency char(3), status text, accessibility jsonb not null default '{}', family_friendly boolean, retrieved_at timestamptz not null default now(), unique(provider,provider_id));
create index events_location_date on public.events(starts_at,latitude,longitude);
create table public.event_provider_records (id uuid primary key default gen_random_uuid(), event_id uuid not null references public.events(id) on delete cascade, provider text not null, raw_payload jsonb not null, payload_hash text not null, retrieved_at timestamptz not null default now());
create table public.places (id uuid primary key default gen_random_uuid(), provider text not null, provider_id text not null, name text not null, category text, address text, latitude numeric(10,7), longitude numeric(10,7), website_url text, booking_url text, price_level integer, rating numeric(3,2), status text, retrieved_at timestamptz not null default now(), unique(provider,provider_id));
create table public.place_provider_records (id uuid primary key default gen_random_uuid(), place_id uuid not null references public.places(id) on delete cascade, provider text not null, raw_payload jsonb not null, payload_hash text not null, retrieved_at timestamptz not null default now());
create table public.host_recommendations (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, place_id uuid references public.places(id), name text not null, category text, host_note text, address text, url text, sponsored boolean not null default false, sort_order integer not null default 0, active boolean not null default true);

create table public.vendors (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id), owner_user_id uuid references auth.users(id), business_name text not null, legal_name text, email citext not null, phone text, service_area text[], categories text[], description text, booking_url text, commission_terms text, approval_status text not null default 'pending', refund_policy text, insurance_path text, license_path text, approved_by uuid references auth.users(id), approved_at timestamptz, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.vendor_services (id uuid primary key default gen_random_uuid(), vendor_id uuid not null references public.vendors(id) on delete cascade, name text not null, description text, price_from numeric(12,2), currency char(3) default 'USD', availability jsonb not null default '{}', fulfillment_details text, active boolean not null default true);
create table public.vendor_documents (id uuid primary key default gen_random_uuid(), vendor_id uuid not null references public.vendors(id) on delete cascade, document_type text not null, storage_path text not null, expires_at date, verified_at timestamptz, verified_by uuid references auth.users(id));
create table public.upgrades (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), property_id uuid references public.properties(id), vendor_id uuid references public.vendors(id), name text not null, description text not null, image_paths text[] not null default '{}', unit_price numeric(12,2) not null, currency char(3) not null default 'USD', tax_category text, lead_time_hours integer not null default 0, quantity_limit integer, blackout_dates daterange[], host_margin numeric(12,2) not null default 0, platform_fee numeric(12,2) not null default 0, refund_terms text not null, approval_required boolean not null default false, fulfillment_checklist jsonb not null default '[]', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.upgrade_availability (id uuid primary key default gen_random_uuid(), upgrade_id uuid not null references public.upgrades(id) on delete cascade, available_date date not null, quantity integer, unavailable boolean not null default false, unique(upgrade_id,available_date));
create table public.upgrade_orders (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), reservation_id uuid not null references public.reservations(id), guest_id uuid references public.guests(id), status public.payment_status not null default 'pending', currency char(3) not null, subtotal numeric(12,2) not null, tax numeric(12,2) not null default 0, total numeric(12,2) not null, stripe_checkout_session_id text unique, stripe_payment_intent_id text unique, idempotency_key text not null unique, created_at timestamptz not null default now(), paid_at timestamptz, cancelled_at timestamptz);
create table public.upgrade_order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.upgrade_orders(id) on delete cascade, upgrade_id uuid not null references public.upgrades(id), name_snapshot text not null, unit_price numeric(12,2) not null, quantity integer not null, total numeric(12,2) not null, fulfillment_status text not null default 'pending');

create table public.cleaning_assignments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), property_id uuid not null references public.properties(id), reservation_id uuid references public.reservations(id), cleaner_member_id uuid not null references public.organization_members(id), backup_cleaner_member_id uuid references public.organization_members(id), status public.job_status not null default 'pending', scheduled_start timestamptz, due_at timestamptz not null, started_at timestamptz, completed_at timestamptz, approved_at timestamptz, rate numeric(12,2), currency char(3), notes text, payout_status text not null default 'unpaid', created_at timestamptz not null default now());
create table public.cleaning_checklists (id uuid primary key default gen_random_uuid(), cleaning_assignment_id uuid not null references public.cleaning_assignments(id) on delete cascade, room text not null, item text not null, required boolean not null default true, completed_at timestamptz, notes text, sort_order integer not null default 0);
create table public.cleaning_photos (id uuid primary key default gen_random_uuid(), cleaning_assignment_id uuid not null references public.cleaning_assignments(id) on delete cascade, storage_path text not null, photo_type text not null, checklist_id uuid references public.cleaning_checklists(id), created_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.maintenance_tickets (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), property_id uuid not null references public.properties(id), reservation_id uuid references public.reservations(id), reported_by uuid references auth.users(id), assigned_vendor_id uuid references public.vendors(id), severity text not null, category text not null, title text not null, description text not null, evidence_paths text[] not null default '{}', status text not null default 'open', approval_limit numeric(12,2), scheduled_at timestamptz, completed_at timestamptz, invoice_path text, warranty_notes text, property_block_required boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.maintenance_quotes (id uuid primary key default gen_random_uuid(), maintenance_ticket_id uuid not null references public.maintenance_tickets(id) on delete cascade, vendor_id uuid not null references public.vendors(id), amount numeric(12,2) not null, currency char(3) not null, details text not null, valid_until date, status text not null default 'pending', created_at timestamptz not null default now());

create table public.inventory_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), property_id uuid not null references public.properties(id), name text not null, unit text not null, par_level numeric(12,2) not null, current_quantity numeric(12,2) not null default 0, unit_cost numeric(12,2), vendor_id uuid references public.vendors(id), active boolean not null default true, unique(property_id,name));
create table public.inventory_counts (id uuid primary key default gen_random_uuid(), inventory_item_id uuid not null references public.inventory_items(id) on delete cascade, quantity numeric(12,2) not null, counted_by uuid not null references auth.users(id), cleaning_assignment_id uuid references public.cleaning_assignments(id), counted_at timestamptz not null default now());
create table public.restock_tasks (id uuid primary key default gen_random_uuid(), inventory_item_id uuid not null references public.inventory_items(id), assigned_to uuid references auth.users(id), quantity numeric(12,2) not null, estimated_cost numeric(12,2), status text not null default 'open', due_at timestamptz, purchase_record jsonb, created_at timestamptz not null default now());

create table public.approvals (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), property_id uuid references public.properties(id), reservation_id uuid references public.reservations(id), requestor_id uuid not null references auth.users(id), approval_type text not null, amount numeric(12,2), currency char(3), reason text not null, supporting_paths text[] not null default '{}', ai_recommendation text, approver_id uuid references auth.users(id), status public.approval_status not null default 'pending', expires_at timestamptz, decision_notes text, decided_at timestamptz, created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, organization_id uuid references public.organizations(id), property_id uuid references public.properties(id), type text not null, priority text not null default 'normal', title text not null, body text not null, deep_link text, read_at timestamptz, created_at timestamptz not null default now());

create table public.subscriptions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), stripe_subscription_id text unique, stripe_customer_id text not null, plan text not null, status text not null, current_period_end timestamptz, trial_end timestamptz, grace_until timestamptz, cancel_at_period_end boolean not null default false, updated_at timestamptz not null default now());
create table public.entitlements (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), feature text not null, enabled boolean not null, usage_limit integer, source text not null, expires_at timestamptz, unique(organization_id,feature));
create table public.payments (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id), upgrade_order_id uuid references public.upgrade_orders(id), stripe_payment_intent_id text unique, amount numeric(12,2) not null, currency char(3) not null, status public.payment_status not null, created_at timestamptz not null default now());
create table public.refunds (id uuid primary key default gen_random_uuid(), payment_id uuid not null references public.payments(id), stripe_refund_id text unique, amount numeric(12,2) not null, reason text, status text not null, created_at timestamptz not null default now());
create table public.commissions (id uuid primary key default gen_random_uuid(), upgrade_order_id uuid not null references public.upgrade_orders(id), vendor_id uuid references public.vendors(id), host_amount numeric(12,2) not null, platform_amount numeric(12,2) not null, vendor_amount numeric(12,2) not null, status text not null default 'pending');
create table public.payouts (id uuid primary key default gen_random_uuid(), vendor_id uuid references public.vendors(id), organization_id uuid references public.organizations(id), amount numeric(12,2) not null, currency char(3) not null, status text not null default 'ledger_only', stripe_transfer_id text, created_at timestamptz not null default now());

create table public.audit_reports (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), property_id uuid not null references public.properties(id), status text not null default 'pending', overall_score numeric(5,2), source_paths text[] not null default '{}', prompt_version text, generated_at timestamptz, created_at timestamptz not null default now());
create table public.audit_findings (id uuid primary key default gen_random_uuid(), audit_report_id uuid not null references public.audit_reports(id) on delete cascade, category text not null, score numeric(5,2), severity text not null, title text not null, details text not null, recommendation text not null, financial_estimate jsonb, sort_order integer not null default 0);
create table public.review_imports (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id), source text not null default 'manual', review_date date, rating numeric(2,1), review_text text not null, reviewer_alias text, consent_basis text, imported_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.review_insights (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id), category text not null, sentiment text not null, evidence_review_ids uuid[] not null, summary text not null, recommendation text, created_at timestamptz not null default now());

create table public.prompt_versions (id uuid primary key default gen_random_uuid(), prompt_key text not null, version integer not null, system_template text not null, output_schema jsonb not null, active boolean not null default false, created_at timestamptz not null default now(), unique(prompt_key,version));
insert into public.prompt_versions(prompt_key,version,system_template,output_schema,active) values ('trip_planner',1,'Create a structured itinerary using only the supplied provider facts. Never invent a business, event, price, address, link, availability, or factual claim. Mark cost estimates explicitly. Preserve identifiers and URLs exactly.','{"type":"object","required":["days","warnings"]}',true);
create table public.ai_runs (id uuid primary key default gen_random_uuid(), request_type text not null, user_id uuid references auth.users(id), organization_id uuid references public.organizations(id), property_id uuid references public.properties(id), reservation_id uuid references public.reservations(id), prompt_version_id uuid not null references public.prompt_versions(id), model text not null, input_source_references jsonb not null, input_redacted jsonb not null, output jsonb, approval_status text not null default 'not_required', execution_status text not null default 'pending', error_status text, created_at timestamptz not null default now(), completed_at timestamptz);
create table public.webhook_events (id uuid primary key default gen_random_uuid(), provider text not null, provider_event_id text not null, payload_hash text not null, status text not null default 'received', attempts integer not null default 0, error_message text, received_at timestamptz not null default now(), processed_at timestamptz, unique(provider,provider_event_id));
create table public.integration_logs (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id), property_id uuid references public.properties(id), provider text not null, action text not null, status text not null, reference_id text not null, technical_context jsonb not null default '{}', created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_user_id uuid references auth.users(id), organization_id uuid references public.organizations(id), action text not null, target_table text, target_id uuid, request_id text, ip_hash text, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.support_cases (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id), opened_by uuid not null references auth.users(id), assigned_to uuid references auth.users(id), subject text not null, description text not null, priority text not null default 'normal', status text not null default 'open', reference_id text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index organization_members_user on public.organization_members(user_id,organization_id) where status='active';
create index notifications_user_unread on public.notifications(user_id,created_at desc) where read_at is null;
create index cleaning_due on public.cleaning_assignments(property_id,due_at) where status not in ('approved','cancelled');
create index maintenance_open on public.maintenance_tickets(property_id,severity,created_at desc) where status not in ('completed','cancelled');
create index approvals_pending on public.approvals(organization_id,created_at desc) where status='pending';
create index ai_runs_org_created on public.ai_runs(organization_id,created_at desc);
create index audit_logs_org_created on public.audit_logs(organization_id,created_at desc);

create or replace function public.is_org_member(org_id uuid, allowed_roles public.app_role[] default null) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.organization_members m where m.organization_id=org_id and m.user_id=auth.uid() and m.status='active' and (allowed_roles is null or m.role=any(allowed_roles)));
$$;
revoke all on function public.is_org_member(uuid,public.app_role[]) from public; grant execute on function public.is_org_member(uuid,public.app_role[]) to authenticated;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,full_name) values(new.id,new.raw_user_meta_data->>'full_name') on conflict do nothing; return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

do $$ declare t text; begin foreach t in array array[
 'profiles','organizations','organization_members','properties','property_amenities','property_photos','property_rules','property_integrations','calendar_sources','reservation_sync_runs','reservations','guests','guest_preferences','guest_consents','guest_portal_tokens','guest_messages','trip_plans','trip_days','trip_items','trip_collaborators','events','event_provider_records','places','place_provider_records','host_recommendations','upgrades','upgrade_availability','upgrade_orders','upgrade_order_items','vendors','vendor_services','vendor_documents','cleaning_assignments','cleaning_checklists','cleaning_photos','maintenance_tickets','maintenance_quotes','inventory_items','inventory_counts','restock_tasks','approvals','notifications','subscriptions','entitlements','payments','refunds','commissions','payouts','audit_reports','audit_findings','review_imports','review_insights','ai_runs','prompt_versions','webhook_events','integration_logs','audit_logs','support_cases'
 ] loop execute format('alter table public.%I enable row level security',t); execute format('alter table public.%I force row level security',t); end loop; end $$;

create policy profiles_self on public.profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy org_member_read on public.organizations for select to authenticated using(public.is_org_member(id));
create policy org_create on public.organizations for insert to authenticated with check(created_by=auth.uid());
create policy org_owner_update on public.organizations for update to authenticated using(public.is_org_member(id,array['host_owner']::public.app_role[]));
create policy members_read on public.organization_members for select to authenticated using(user_id=auth.uid() or public.is_org_member(organization_id,array['host_owner','host_manager']::public.app_role[]));
create policy members_manage on public.organization_members for all to authenticated using(public.is_org_member(organization_id,array['host_owner','host_manager']::public.app_role[])) with check(public.is_org_member(organization_id,array['host_owner','host_manager']::public.app_role[]));

create policy properties_read on public.properties for select to authenticated using(public.is_org_member(organization_id));
create policy properties_manage on public.properties for all to authenticated using(public.is_org_member(organization_id,array['host_owner','host_manager']::public.app_role[])) with check(public.is_org_member(organization_id,array['host_owner','host_manager']::public.app_role[]));
create policy reservations_read on public.reservations for select to authenticated using(public.is_org_member(organization_id) or guest_id in(select id from public.guests where profile_id=auth.uid()));
create policy reservations_manage on public.reservations for all to authenticated using(public.is_org_member(organization_id,array['host_owner','host_manager','property_staff']::public.app_role[])) with check(public.is_org_member(organization_id,array['host_owner','host_manager','property_staff']::public.app_role[]));
create policy guests_org on public.guests for all to authenticated using(public.is_org_member(organization_id) or profile_id=auth.uid()) with check(public.is_org_member(organization_id) or profile_id=auth.uid());
create policy trip_owner on public.trip_plans for all to authenticated using(owner_user_id=auth.uid() or public.is_org_member(organization_id)) with check(owner_user_id=auth.uid() or public.is_org_member(organization_id));
create policy notifications_self on public.notifications for select to authenticated using(user_id=auth.uid());
create policy notifications_update_self on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy cleaning_assigned on public.cleaning_assignments for select to authenticated using(public.is_org_member(organization_id) and (cleaner_member_id in(select id from public.organization_members where user_id=auth.uid()) or public.is_org_member(organization_id,array['host_owner','host_manager','property_staff']::public.app_role[])));
create policy cleaning_manage on public.cleaning_assignments for all to authenticated using(public.is_org_member(organization_id,array['host_owner','host_manager','property_staff']::public.app_role[]) or cleaner_member_id in(select id from public.organization_members where user_id=auth.uid())) with check(public.is_org_member(organization_id));
create policy maintenance_org on public.maintenance_tickets for all to authenticated using(public.is_org_member(organization_id)) with check(public.is_org_member(organization_id));
create policy approvals_org on public.approvals for select to authenticated using(public.is_org_member(organization_id));
create policy approvals_request on public.approvals for insert to authenticated with check(requestor_id=auth.uid() and public.is_org_member(organization_id));
create policy approvals_decide on public.approvals for update to authenticated using(public.is_org_member(organization_id,array['host_owner','host_manager']::public.app_role[])) with check(public.is_org_member(organization_id,array['host_owner','host_manager']::public.app_role[]));
create policy public_events_read on public.events for select to anon,authenticated using(true);
create policy public_places_read on public.places for select to anon,authenticated using(true);
create policy active_recommendations_read on public.host_recommendations for select to anon,authenticated using(active=true);
create policy active_upgrades_read on public.upgrades for select to anon,authenticated using(active=true);
create policy prompt_versions_server_read on public.prompt_versions for select to authenticated using(active=true);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
 ('property-photos','property-photos',false,15728640,array['image/jpeg','image/png','image/webp','image/heic']),
 ('guest-files','guest-files',false,15728640,array['image/jpeg','image/png','image/webp','application/pdf']),
 ('cleaning-photos','cleaning-photos',false,15728640,array['image/jpeg','image/png','image/webp','image/heic']),
 ('maintenance-evidence','maintenance-evidence',false,26214400,array['image/jpeg','image/png','image/webp','video/mp4','application/pdf']),
 ('vendor-documents','vendor-documents',false,26214400,array['application/pdf','image/jpeg','image/png']),
 ('audit-uploads','audit-uploads',false,26214400,array['application/pdf','image/jpeg','image/png','image/webp']),
 ('guidebook-files','guidebook-files',false,26214400,array['application/pdf','image/jpeg','image/png','image/webp'])
on conflict(id) do nothing;

commit;
