import { env } from "@/lib/env";
export type EventResult={provider:"ticketmaster";providerId:string;name:string;category:string|null;venue:string|null;address:string|null;latitude:number|null;longitude:number|null;startsAt:string;timezone:string|null;ticketUrl:string;imageUrl:string|null;priceMin:number|null;priceMax:number|null;currency:string|null;status:string|null;familyFriendly:boolean|null;retrievedAt:string};
export async function searchEvents(input:{city:string;startDate:string;endDate:string;radius?:number;keyword?:string}):Promise<EventResult[]>{
  if(!env.TICKETMASTER_API_KEY)throw new Error("TICKETMASTER_SETUP_REQUIRED");
  const q=new URLSearchParams({apikey:env.TICKETMASTER_API_KEY,city:input.city,startDateTime:`${input.startDate}T00:00:00Z`,endDateTime:`${input.endDate}T23:59:59Z`,radius:String(input.radius??50),unit:"miles",size:"50",sort:"date,asc"});if(input.keyword)q.set("keyword",input.keyword);
  const response=await fetch(`https://app.ticketmaster.com/discovery/v2/events.json?${q}`,{next:{revalidate:900}});if(!response.ok)throw new Error(`TICKETMASTER_${response.status}`);
  const body=await response.json() as { _embedded?:{events?:Array<Record<string,unknown>>}};
  return (body._embedded?.events??[]).map(raw=>{const embedded=raw._embedded as {venues?:Array<Record<string,unknown>>}|undefined;const venue=embedded?.venues?.[0];const dates=raw.dates as Record<string,any>|undefined;const sales=raw.priceRanges as Array<Record<string,unknown>>|undefined;const images=raw.images as Array<Record<string,unknown>>|undefined;const classifications=raw.classifications as Array<Record<string,any>>|undefined;return {provider:"ticketmaster",providerId:String(raw.id),name:String(raw.name),category:classifications?.[0]?.segment?.name??null,venue:venue?.name?String(venue.name):null,address:venue?`${(venue.address as any)?.line1??""}, ${(venue.city as any)?.name??""}, ${(venue.state as any)?.stateCode??""}`.replace(/^, |, $/g,""):null,latitude:venue?.location?Number((venue.location as any).latitude):null,longitude:venue?.location?Number((venue.location as any).longitude):null,startsAt:String(dates?.start?.dateTime??`${dates?.start?.localDate}T${dates?.start?.localTime??"00:00:00"}`),timezone:venue?.timezone?String(venue.timezone):null,ticketUrl:String(raw.url),imageUrl:images?.[0]?.url?String(images[0].url):null,priceMin:sales?.[0]?.min==null?null:Number(sales[0].min),priceMax:sales?.[0]?.max==null?null:Number(sales[0].max),currency:sales?.[0]?.currency?String(sales[0].currency):null,status:dates?.status?.code??null,familyFriendly:null,retrievedAt:new Date().toISOString()};});
}
